class AddColumnsToTicketVehicles < ActiveRecord::Migration
 def change
    add_column :ticket_vehicles, :mirror_broken, :integer
    add_column :ticket_vehicles, :mirror_working, :integer
    add_column :ticket_vehicles, :mirror_placed, :integer
    add_column :ticket_vehicles, :tires_inflated, :integer
    add_column :ticket_vehicles, :tires_properly_inflated, :integer
    add_column :ticket_vehicles, :tires_tread, :integer
    add_column :ticket_vehicles, :windows_broken, :integer
    add_column :ticket_vehicles, :windows_missing, :integer
    add_column :ticket_vehicles, :doors_broken, :integer
    add_column :ticket_vehicles, :doors_dented, :integer
    add_column :ticket_vehicles, :doors_latched, :integer
    add_column :ticket_vehicles, :brakes_worn, :integer
    add_column :ticket_vehicles, :brakes_missing, :integer
    add_column :ticket_vehicles, :brakes_damaged, :integer
    add_column :ticket_vehicles, :fifth_wheel_locked, :integer
    add_column :ticket_vehicles, :fifth_wheel_greased, :integer
    add_column :ticket_vehicles, :fifth_wheel_abnormal, :integer
    add_column :ticket_vehicles, :hoses_secured, :integer
    add_column :ticket_vehicles, :hoses_hanging, :integer
    add_column :ticket_vehicles, :hoses_leaks, :integer
    add_column :ticket_vehicles, :hoses_wear, :integer
    add_column :ticket_vehicles, :flags_secured, :integer
    add_column :ticket_vehicles, :flags_serviceable, :integer
    add_column :ticket_vehicles, :rear_bumper_loose, :integer
    add_column :ticket_vehicles, :rear_bumper_missing, :integer
    add_column :ticket_vehicles, :rear_bumper_damaged, :integer
    add_column :ticket_vehicles, :license_plate_dirty, :integer
    add_column :ticket_vehicles, :license_plate_attached, :integer
    add_column :ticket_vehicles, :license_plate_sticker, :integer
    add_column :ticket_vehicles, :truck_bed_tire, :integer
    add_column :ticket_vehicles, :truck_bed_jack, :integer
    add_column :ticket_vehicles, :truck_bed_wrench, :integer
    add_column :ticket_vehicles, :truck_bed_debris, :integer
    add_column :ticket_vehicles, :truck_bed_tools, :integer
    add_column :ticket_vehicles, :truck_bed_clean, :integer
    add_column :ticket_vehicles, :brake_lights_working, :integer
    add_column :ticket_vehicles, :rear_window_broken, :integer
    add_column :ticket_vehicles, :rear_window_missing, :integer
    add_column :ticket_vehicles, :rear_window_clean, :integer
    add_column :ticket_vehicles, :air_bags_leaks, :integer
    add_column :ticket_vehicles, :headlights_brights_working, :integer
    add_column :ticket_vehicles, :headlights_low_beams_working, :integer
    add_column :ticket_vehicles, :turn_signals_working, :integer
    add_column :ticket_vehicles, :front_bumper_attached, :integer
    add_column :ticket_vehicles, :windshield_broken, :integer
    add_column :ticket_vehicles, :windshield_missing, :integer
    add_column :ticket_vehicles, :windshield_clean, :integer
    add_column :ticket_vehicles, :wiper_blades_broken, :integer
    add_column :ticket_vehicles, :wiper_blades_working, :integer
    add_column :ticket_vehicles, :overall_interior_clean, :integer
    add_column :ticket_vehicles, :parking_brake_working, :integer
    add_column :ticket_vehicles, :horn_working, :integer
    add_column :ticket_vehicles, :seat_belts_working, :integer
    add_column :ticket_vehicles, :seat_belts_frayed, :integer
    add_column :ticket_vehicles, :seat_belts_cut, :integer
    add_column :ticket_vehicles, :seat_belts_torn, :integer
    add_column :ticket_vehicles, :seat_belts_snagged, :integer
    add_column :ticket_vehicles, :seat_belts_roping, :integer
    add_column :ticket_vehicles, :gauges_working, :integer
    add_column :ticket_vehicles, :rearview_mirror_placed, :integer
    add_column :ticket_vehicles, :rearview_mirror_working, :integer
    add_column :ticket_vehicles, :rearview_mirror_clean, :integer
    add_column :ticket_vehicles, :registration_present, :integer
    add_column :ticket_vehicles, :registration_current, :integer
    add_column :ticket_vehicles, :fluids_add, :integer
    add_column :ticket_vehicles, :deficiences_corrected, :integer
    add_column :ticket_vehicles, :permits_paperwork_present, :integer
    add_column :ticket_vehicles, :permits_paperwork_current, :integer
    add_column :ticket_vehicles, :chains_binders_present, :integer
    add_column :ticket_vehicles, :chains_binders_serviceable, :integer
    add_column :ticket_vehicles, :mirror_broken_explanation, :string
    add_column :ticket_vehicles, :mirror_working_explanation, :string
    add_column :ticket_vehicles, :mirror_placed_explanation, :string
    add_column :ticket_vehicles, :tires_properly_inflated_explanation, :string
    add_column :ticket_vehicles, :tires_tread_explanation, :string
    add_column :ticket_vehicles, :windows_broken_explanation, :string
    add_column :ticket_vehicles, :windows_missing_explanation, :string
    add_column :ticket_vehicles, :doors_broken_explanation, :string
    add_column :ticket_vehicles, :doors_dented_explanation, :string
    add_column :ticket_vehicles, :doors_latched_explanation, :string
    add_column :ticket_vehicles, :brakes_worn_explanation, :string
    add_column :ticket_vehicles, :brakes_missing_explanation, :string
    add_column :ticket_vehicles, :brakes_damaged_explanation, :string
    add_column :ticket_vehicles, :fifth_wheel_locked_explanation, :string
    add_column :ticket_vehicles, :fifth_wheel_greased_explanation, :string
    add_column :ticket_vehicles, :fifth_wheel_abnormal_explanation, :string
    add_column :ticket_vehicles, :hoses_secured_explanation, :string
    add_column :ticket_vehicles, :hoses_hanging_explanation, :string
    add_column :ticket_vehicles, :hoses_leaks_explanation, :string
    add_column :ticket_vehicles, :hoses_wear_explanation, :string
    add_column :ticket_vehicles, :flags_secured_explanation, :string
    add_column :ticket_vehicles, :flags_serviceable_explanation, :string
    add_column :ticket_vehicles, :rear_bumper_loose_explanation, :string
    add_column :ticket_vehicles, :rear_bumper_missing_explanation, :string
    add_column :ticket_vehicles, :rear_bumper_damaged_explanation, :string
    add_column :ticket_vehicles, :license_plate_dirty_explanation, :string
    add_column :ticket_vehicles, :license_plate_attached_explanation, :string
    add_column :ticket_vehicles, :license_plate_sticker_explanation, :string
    add_column :ticket_vehicles, :truck_bed_tire_explanation, :string
    add_column :ticket_vehicles, :truck_bed_jack_explanation, :string
    add_column :ticket_vehicles, :truck_bed_wrench_explanation, :string
    add_column :ticket_vehicles, :truck_bed_debris_explanation, :string
    add_column :ticket_vehicles, :truck_bed_tools_explanation, :string
    add_column :ticket_vehicles, :truck_bed_clean_explanation, :string
    add_column :ticket_vehicles, :brake_lights_working_explanation, :string
    add_column :ticket_vehicles, :rear_window_broken_explanation, :string
    add_column :ticket_vehicles, :rear_window_missing_explanation, :string
    add_column :ticket_vehicles, :rear_window_clean_explanation, :string
    add_column :ticket_vehicles, :air_bags_leaks_explanation, :string
    add_column :ticket_vehicles, :headlights_brights_working_explanation, :string
    add_column :ticket_vehicles, :headlights_low_beams_working_explanation, :string
    add_column :ticket_vehicles, :turn_signals_working_explanation, :string
    add_column :ticket_vehicles, :front_bumper_attached_explanation, :string
    add_column :ticket_vehicles, :windshield_broken_explanation, :string
    add_column :ticket_vehicles, :windshield_missing_explanation, :string
    add_column :ticket_vehicles, :windshield_clean_explanation, :string
    add_column :ticket_vehicles, :wiper_blades_broken_explanation, :string
    add_column :ticket_vehicles, :wiper_blades_working_explanation, :string
    add_column :ticket_vehicles, :overall_interior_clean_explanation, :string
    add_column :ticket_vehicles, :parking_brake_working_explanation, :string
    add_column :ticket_vehicles, :horn_working_explanation, :string
    add_column :ticket_vehicles, :seat_belts_working_explanation, :string
    add_column :ticket_vehicles, :seat_belts_frayed_explanation, :string
    add_column :ticket_vehicles, :seat_belts_cut_explanation, :string
    add_column :ticket_vehicles, :seat_belts_torn_explanation, :string
    add_column :ticket_vehicles, :seat_belts_snagged_explanation, :string
    add_column :ticket_vehicles, :seat_belts_roping_explanation, :string
    add_column :ticket_vehicles, :gauges_working_explanation, :string
    add_column :ticket_vehicles, :rearview_mirror_placed_explanation, :string
    add_column :ticket_vehicles, :rearview_mirror_working_explanation, :string
    add_column :ticket_vehicles, :rearview_mirror_clean_explanation, :string
    add_column :ticket_vehicles, :registration_present_explanation, :string
    add_column :ticket_vehicles, :registration_current_explanation, :string
    add_column :ticket_vehicles, :fluids_add_explanation, :string
    add_column :ticket_vehicles, :deficiences_corrected_explanation, :string
    add_column :ticket_vehicles, :crew_chief, :string
    add_column :ticket_vehicles, :driver, :string
  end
end
